### ISSUE TITLE
Fails with partial terms contained in other terms

### ISSUE THREAD

**Issue by ps374** [PebbleRoad/glossarizer#7]
If the one term is partially contained in another then it marks up the first term (it received) in another. For example: two different terms are:

1) creature
2) creature kind

Although, "creature kind" is a different term, Glossarizer marks it with "creature", if the above order is followed.

**Comment by dstrang** [comment]
I just ran into the same issue.  The problem is in the getDescription method.  I changed the regex method  to do an exact match: 

```javascript
var regex = new RegExp('^' + this.clean(term) + '$', 'i');
```

I'm not sure if changing the regex will affect anything else, but it was a quick fix for what I needed.  There are other things I would like to improve, so I may do a pull request later.
